version: '3.8'

services:
  #database section
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  tedu.api:
    image: ${DOCKER_REGISTRY-}tedu-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
     context: .
     dockerfile: src/TeduBlog.Api/Dockerfile

#network section
networks:
  default:
    name: tedu_blog
    driver: bridge

#volumes sections
volumes:
  sqlserver_data:
    name: sqlserver_data